import styles from "@/styles/Home.module.css";
import axios from "axios";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Brandon Howard&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800">
        <section className="min-h-screen">
          <nav className="py-10 mb-122 flex justify-between ">
            <h1 className="text-2xl text-gray-800 dark:text-gray-200">
              <a href="index">Brandon Howard</a>
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:text-gray-200"
                />
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-peacock-blue font-medium md:text-6xl dark:text-emerald-green">
              Resume
            </h2>
          </div>
          <div className="flex basis-1/3 rounded-2xl justify-center p-10 sahdow-lg bg-peacock-blue ">
            <object
              data="/assets/resume.pdf"
              type="application/pdf"
              className="object-cover"
              width="75%"
              height="500px"
            >
              <p>
                Unable to display PDF file.
                <a href="/assets/resume.pdf">Download instead.</a>
              </p>
            </object>
          </div>
        </section>
      </main>
    </div>
  );
}
